language: bash

# Only build pushes to master.
branches:
  except:
    - /^\d+$/

env:
  global:
    - CI_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  # Install gcloud
  - rm -rf ${HOME}/google-cloud-sdk
  - curl https://sdk.cloud.google.com | bash;
  - export PATH=${HOME}/google-cloud-sdk/bin:$PATH
  - gcloud components install kubectl

  # Get those secrets out
  - echo $GCP_SECRET > client-secret.json
  - gcloud auth activate-service-account --key-file client-secret.json
  - export GOOGLE_APPLICATION_CREDENTIALS="$TRAVIS_BUILD_DIR/client-secret.json"

install:
  # Install envtpl for easy templating.
  - pip install --user envtpl
  - export PATH="$PATH:${HOME}/.local/bin/"

script:
  - echo "nothing to do here"

after_success:
  - >
    [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] &&
    make deploy
