language: bash

# Only build pushes to master.
branches:
  except:
    - /^\d+$/

env:
  global:
    - CI_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

before_deploy:
  # Install or update GCloud
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source "$HOME/google-cloud-sdk/path.bash.inc"
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components update kubectl

  # Credential GCloud
  - echo $GCP_SECRET > client-secret.json
  - gcloud auth activate-service-account --key-file client-secret.json
  - export GOOGLE_APPLICATION_CREDENTIALS="$TRAVIS_BUILD_DIR/client-secret.json"

  # Install envtpl for easy templating.
  - pip install --user envtpl
  - export PATH="$PATH:${HOME}/.local/bin/"

script:
  - echo "This project does not build"

deploy:
  - provider: script
    script: make deploy
    skip_cleanup: true
    on:
      branch: master
